# This guide is optimized for Vagrant 1.7 and above.
# Although versions 1.6.x should behave very similarly, it is recommended
# to upgrade instead of disabling the requirement below.
Vagrant.require_version ">= 1.7.0"

Vagrant.configure(2) do |config|

    ###########################################################################
    # ALL
    ###########################################################################
    config.vm.box = "bento/ubuntu-16.04"

    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end

    ###########################################################################
    # DEV BOX
    ###########################################################################
    config.vm.define "rancher-host.dev.box" do |dev|
        dev.vm.network "private_network", ip: "127.0.0.1"

        # Forward rancher ports 8080 and 80 (nginx)
        dev.vm.network "forwarded_port", guest: 8080, host: 8080, host_ip: "127.0.0.1"
        dev.vm.network "forwarded_port", guest: 80, host: 8000, host_ip: "127.0.0.1"

        dev.vm.synced_folder "../", "/vagrant_data/", create: true,
            owner: "vagrant",
            group: "vagrant",
            mount_options: ["dmode=775,fmode=775"]

        dev.vm.provision "ansible_local" do |ansible|
            ansible.verbose = true
            ansible.playbook = "/vagrant_data/ansible/development.yml"
            ansible.inventory_path = "/vagrant_data/ansible/development"
        end
    end
end
