---

################################################################################
# Add start script to usr/local/bin
################################################################################

- name: Add rancher start script to usr/local/bin
  template: src=start_rancher.sh.j2 dest=/usr/local/bin/start_rancher.sh owner={{ user_name }} mode=0700
  tags: [rancher, install]

- name: Add nginx start script to usr/local/bin
  template: src=start_nginx.sh.j2 dest=/usr/local/bin/start_nginx.sh owner={{ user_name }} mode=0700
  tags: [rancher, install]

- name: Ensure rancher conf dir exists
  file: path=/etc/rancher state=directory owner={{ user_name }} group={{ user_name }}
  tags: [rancher, install]

- name: Add nginx config
  template: src=nginx.conf.j2 dest=/etc/rancher/nginx.conf owner={{ user_name }} mode=0755
  tags: [rancher, install]

- name: Start the rancher container
  command: /usr/local/bin/start_rancher.sh
  ignore_errors: yes
  tags: [rancher]

- name: Start the nginx container
  command: /usr/local/bin/start_nginx.sh
  ignore_errors: yes
  tags: [rancher]
