# Generated by Django 2.0.3 on 2018-03-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='news item content')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
            ],
            options={
                'verbose_name': 'news item',
                'verbose_name_plural': 'news items',
            },
        ),
    ]
