# Generated by Django 2.0.3 on 2018-03-25 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
